### ISSUE TITLE
issue with building gendy

### ISSUE THREAD

**Issue by shreeswifty** [ssfrr/gendyflext#1]
src/gendy~.cpp: In member function ‘void gendy::redraw()’:
src/gendy~.cpp:239:35: error: no match for ‘operator=’ (operand types are ‘t_word {aka word}’ and ‘gendysamp_t {aka float}’)
   (*display_buf)[n] = temp_buf[n++];
                                   ^
In file included from /usr/local/include/flext/flstdc.h:66:0,
                 from /usr/local/include/flext/flbase.h:18,
                 from /usr/local/include/flext/flclass.h:18,
                 from /usr/local/include/flext/flext.h:60,
                 from src/gendy~.cpp:38:
/usr/include/pd/m_pd.h:151:15: note: candidate: constexpr word& word::operator=(const word&)
 typedef union word
               ^~~~
/usr/include/pd/m_pd.h:151:15: note:   no known conversion for argument 1 from ‘gendysamp_t {aka float}’ to ‘const word&’
/usr/include/pd/m_pd.h:151:15: note: candidate: constexpr word& word::operator=(word&&)
/usr/include/pd/m_pd.h:151:15: note:   no known conversion for argument 1 from ‘gendysamp_t {aka float}’ to ‘word&&’
src/gendy~.cpp:243:24: error: no match for ‘operator=’ (operand types are ‘t_word {aka word}’ and ‘int’)
   (*display_buf)[n++]= 0;
                        ^
In file included from /usr/local/include/flext/flstdc.h:66:0,
                 from /usr/local/include/flext/flbase.h:18,
                 from /usr/local/include/flext/flclass.h:18,
                 from /usr/local/include/flext/flext.h:60,
                 from src/gendy~.cpp:38:
/usr/include/pd/m_pd.h:151:15: note: candidate: constexpr word& word::operator=(const word&)
 typedef union word
               ^~~~
/usr/include/pd/m_pd.h:151:15: note:   no known conversion for argument 1 from ‘int’ to ‘const word&’
/usr/include/pd/m_pd.h:151:15: note: candidate: constexpr word& word::operator=(word&&)
/usr/include/pd/m_pd.h:151:15: note:   no known conversion for argument 1 from ‘int’ to ‘word&&’
/home/pi/Downloads/flext-master/./buildsys/lnx/gnumake-gcc-ext.inc:27: recipe for target 'pd-linux/release-single/gendy~.opp' failed
make[1]: *** [pd-linux/release-single/gendy~.opp] Error 1
make[1]: Leaving directory '/home/pi/Downloads/gendyflext-master'
/home/pi/Downloads/flext-master/./buildsys/targets.inc:62: recipe for target 'build-release-single' failed
make: *** [build-release-single] Error 2

**Comment by ssfrr** [comment]
Unfortunately it's been a really long time since I've been in this code and don't have time these days to dig into issues with it. My guess is that it needs some updating for more recent versions of flext. and/or the PD/Max SDKs.

**Comment by grrrr** [comment]
Should be fixed with flext commit https://github.com/grrrr/flext/commit/c54c07197f1ac5efb2eac340f2723a491a5d0407

**Comment by ssfrr** [comment]
Great, thanks! @shreeswifty LMK if it works when you build with the latest flext and I'll close the issue.

**Comment by shreeswifty** [comment]
Spencer
Built and works! 
BTW I'm Patrick Pagano. I originally did the building of the external for you about 15 years ago when i was in grad school on Redhat :-) ha! i started coding pd for http://organelle.io and was after a nice gendy~ for a while. With Thomas' infinite patience it works again!!!!

**Comment by ssfrr** [comment]
Awesome, thanks both of you, and nice to hear from you again! LMK if you have some nice organelle demos with `gendy~`!
