### ISSUE TITLE
gendyflext fixed

### ISSUE THREAD

**Issue by shreeswifty** [ssfrr/gendyflext#4]
-- gendy~ v0.6.0 by Spencer Russell --
gendy~: please report bugs to http://code.airwav.es/projects/gendy/issues

fixed by Patrick Pagano & Thomas Grill [MOSTLY THOMAS!!] 2017 
Spirit of Xenakis lives on Raspberry pi

**Comment by ssfrr** [comment]
woot - glad things are alive and well!
